# Generated by Django 5.0.7 on 2024-07-27 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Workout Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
